### ISSUE TITLE
Phone not charging/charge very slow.

### ISSUE THREAD

**Issue by dedyoc** [PixelExperience/android-issues#62] opened 2021-05-16 11:51 UTC
## Build date

```
PixelExperience_Plus_cepheus-11.0-20210514-0318-OFFICIAL
```

## Expected Behavior

```
It should be fast charging 
```

## Current Behavior

```
It went up 1% then stopped
```

## Possible Solution

```
I don't know.
```

## Steps to Reproduce

```
1. Charge the phone. 
```

/device cepheus
/version eleven_plus

**Comment by jjpprrrr** [comment] 2021-05-16 11:57
Why did you put a raphael build in the build name, but cepheus under /device?

**Comment by dedyoc** [comment] 2021-05-16 15:32
> Why did you put a raphael build in the build name, but cepheus under /device?

I was copy pasting this issue.

**Comment by jjpprrrr** [comment] 2021-05-17 00:36
I cannot reproduce the issue on cepheus. The charging speed is normal using both the wired charger and a wireless charger. Please check your USB type C port, the cable, or the charger.

**Comment by dedyoc** [comment] 2021-05-17 00:40
I think this is a hardware issue, my battery has already degraded a lot. It can still charge in recovery mode.

**Comment by dedyoc** [comment] 2021-05-17 10:23
I installed xiaomi.eu android 10 and things are normal now.

**Comment by EcrosoftXiao** [comment] 2021-05-17 11:13
> I installed xiaomi.eu android 10 and things are normal now.

Since I can't reproduce your issue either. Can you send me any logcat and your temperature of xo_therm and quiet_therm when you plug in your charger?

Btw there was another guy enter into charging issue also but fixed by switching to another cable. Can your try charging with another cable/adapter?

**Comment by dedyoc** [comment] 2021-05-17 11:37
I'm not sure if i can but I will try it later.

**Comment by wsay-kx99** [comment] 2021-05-28 08:47
Another person also has this problem. Its solution is to replace the data cable. This may be related to your data cable. Please try again after replacing the data cable.

**Closed** 2021-06-13 17:07 UTC
Labels: device:cepheus, eleven_plus, validated
