### ISSUE TITLE
Gcam Stuck on HDR+ Processing

### ISSUE THREAD

**Issue by Theavudd** [PixelExperience/android-issues#299] opened 2021-07-05 05:25 UTC
## Build date

```
PixelExperience_Plus_beryllium-11.0-20210622-0854-OFFICIAL
```

## Expected Behavior

```
The camera should save the image into the storage
```

## Current Behavior

```
Whenever i am installing a gcam version after the update and click an image it is stuck on hdr+ processing ,tried various gcam ports and tried restarting as well. Also done a clean flash this update.
```

## Possible Solution

```

```

## Steps to Reproduce

```
1.
![Screenshot_20210705-104253_Camera](https://user-images.githubusercontent.com/82509758/124421590-67621b80-dd7f-11eb-8760-dadaae3849c3.png)

2.
3.
4.
```

/device beryllium
/version eleven_plus

**Comment by cyberelon** [comment] 2021-07-05 12:14
This bug has been fixed in internal test builds, so please use Parrot Cam for the time being until a bug fix build or July build is released.

**Comment by cyberelon** [comment] 2021-07-05 12:25
Duplicated #297

**Comment by aravindvnair99** [comment] 2021-08-22 10:20
@lakgarg @Hlcpereira @jhenrique09 This can be closed. Was not working in June build but is working in July build. Also, a duplicate of #297 as @cyberelon mentioned.

**Closed** 2021-08-22 15:15 UTC
Labels: validated, eleven_plus, device:beryllium
